apiVersion: apps/v1
kind: Deployment
metadata:
  name: guest-v1
  labels:
    app: guest
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guest
      version: v1
  template:
    metadata:
      labels:
        app: guest
        version: v1
    spec:
      containers:
      - name: guest
        image: ghcr.io/patricksferraz/guest
        ports:
        - name: rest
          containerPort: 8080
        envFrom:
          - secretRef:
              name: guest-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"

      imagePullSecrets:
          - name: regsecret
