apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendant-v1
  labels:
    app: attendant
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendant
      version: v1
  template:
    metadata:
      labels:
        app: attendant
        version: v1
    spec:
      containers:
      - name: attendant
        image: ghcr.io/patricksferraz/attendant
        ports:
        - name: rest
          containerPort: 8080
        envFrom:
          - secretRef:
              name: attendant-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"

      imagePullSecrets:
          - name: regsecret
