apiVersion: v1
kind: Service
metadata:
  name: attendant
  labels:
    app: attendant
    service: attendant
spec:
  type: ClusterIP
  selector:
    app: attendant
  ports:
  - name: rest
    port: 8080
    targetPort: 8080
